### ISSUE TITLE
Syntax: use (.method obj ...) syntax

### ISSUE THREAD

**Issue by oubiwann** [Element84/clj-gdal#5]
The dot special form in Clojure's Java interop support is considered a low-level form. The Clojure Java interop docs show the preferred methodologies for access at the top of the page (with the special form getting a description below that):
- http://clojure.org/java_interop

The Clojure Style Guide suggests the same:
- https://github.com/bbatsov/clojure-style-guide

(You'll need to search for "java" in the page...)

**Comment by jmorton** [comment]
Thanks for pointing this out @oubiwann – I've merged a pull request to fix this!
